apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-idp
  labels:
    app: mock-idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-idp
  template:
    metadata:
      labels:
        app: mock-idp
    spec:
      containers:
        - name: mock-idp
          image: mock-idp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mock-idp
spec:
  selector:
    app: mock-idp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
