apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-idp
  labels:
    app: mock-idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-idp
  template:
    metadata:
      labels:
        app: mock-idp
    spec:
      containers:
        - name: mock-idp
          image: mock-idp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
          - mountPath: /idp.key
            name: idp-ds-tls-volume
            subPath: tls.key
          - mountPath: /idp.crt
            name: idp-ds-tls-volume
            subPath: tls.crt
      volumes:
      - name: idp-ds-tls-volume
        secret:
          defaultMode: 420
          secretName: apk-wso2-kgw-idp-ds-server-cert

---
apiVersion: v1
kind: Service
metadata:
  name: mock-idp
spec:
  selector:
    app: mock-idp
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
